// Temporary Firebase configuration placeholder.
//
// This file allows the project to compile while you set up
// real Firebase configuration using the FlutterFire CLI:
//   flutterfire configure --project=<your-project-id>
//
// That command will overwrite this file with the correct values.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // TODO: Replace with real web config generated by FlutterFire.
      return const FirebaseOptions(
        apiKey: 'YOUR_WEB_API_KEY',
        appId: 'YOUR_WEB_APP_ID',
        messagingSenderId: 'YOUR_SENDER_ID',
        projectId: 'YOUR_PROJECT_ID',
      );
    }

    // TODO: Add Android, iOS, macOS, Windows configs as needed.
    // For now, return a dummy config that will likely fail at runtime
    // until you generate real options via flutterfire configure.
    return const FirebaseOptions(
      apiKey: 'DUMMY_KEY',
      appId: 'DUMMY_APP_ID',
      messagingSenderId: 'DUMMY_SENDER_ID',
      projectId: 'DUMMY_PROJECT_ID',
    );
  }
}

